//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CNPM_DOAN.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class BAIGIAI
    {
        public string IDBaiGiai { get; set; }
        public string TenBaiGiai { get; set; }
        public byte[] DuongDan { get; set; }
        public string LoaiTep { get; set; }
        public Nullable<double> SoDiem { get; set; }
        public Nullable<System.DateTime> NgayHoanThanh { get; set; }
        public string IDNguoiDung { get; set; }
        public string IDBaiTap { get; set; }
    
        public virtual BAITAP BAITAP { get; set; }
        public virtual NGUOIDUNG NGUOIDUNG { get; set; }
    }
}
