//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CNPM_DOAN.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    using System.Data;
    using System.Data.Entity;
    using System.Linq;
    using System.Net;
    using System.Web;
    using System.Web.Mvc;
    using System.Web.UI.WebControls;

    public partial class BAITAP
    {
        private CNPM_DOANEntities db = new CNPM_DOANEntities();
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public BAITAP()
        {
            this.BAIGIAIs = new HashSet<BAIGIAI>();
        }

        public string IDBaiTap { get; set; }
        public string TenBT { get; set; }
        public Nullable<System.DateTime> NgayGiao { get; set; }
        public Nullable<System.DateTime> HanNop { get; set; }
        public string IDNguoiTao { get; set; }
        public string IDNguoiNhan { get; set; }
        public byte[] DuongDan { get; set; }
        public string LoaiTep { get; set; }

        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<BAIGIAI> BAIGIAIs { get; set; }
        public virtual NGUOIDUNG NGUOIDUNG { get; set; }
        public virtual NGUOIDUNG NGUOIDUNG1 { get; set; }
        public bool KTBaiGiai(string iduser, string idbaitap)
        {
            var data = db.BAIGIAIs.Where(s => s.IDBaiTap == idbaitap && s.IDNguoiDung == iduser).ToList();
            if (data.Count == 0) return false;
            else return true;
        }
    }
}
