//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CNPM_DOAN.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class THOIKHOABIEU
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public THOIKHOABIEU()
        {
            this.TIETHOCs = new HashSet<TIETHOC>();
        }
    
        public string IDTKB { get; set; }
        [Required(ErrorMessage ="Yêu cầu nhập tên thời khóa biểu")]
        public string TenTKB { get; set; }
        public string IDNguoiDung { get; set; }
    
        public virtual NGUOIDUNG NGUOIDUNG { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TIETHOC> TIETHOCs { get; set; }
    }
}
