//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CNPM_DOAN.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TIETHOC
    {
        public string IDMonHoc { get; set; }
        public string TenMH { get; set; }
        public string Thu { get; set; }
        public short TietBatDau { get; set; }
        public short TietKetThuc { get; set; }
        public string IDTKB { get; set; }
        public string IDNGUOITAO { get; set; }
    
        public virtual NGUOIDUNG NGUOIDUNG { get; set; }
        public virtual THOIKHOABIEU THOIKHOABIEU { get; set; }
    }
}
